import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = join(import.meta.dirname, "..");

describe("BNB AI Network web application", () => {
  it("provides an open public explorer, global worker map, docs, and private workspace routes", async () => {
    const html = await readFile(join(root, "public", "index.html"), "utf8");
    expect(html).toContain("BNB AI NETWORK");
    expect(html).toContain('id="access-form"');
    expect(html).toContain('id="public-request-form"');
    const requestDialog = html.match(/<div id="access-overlay"[\s\S]*?<\/div>\s*<div id="workspace-overlay"/)?.[0] ?? "";
    expect(requestDialog).not.toContain("Open the private beta workspace");
    expect(requestDialog).not.toContain('id="access-form"');
    expect(html).toContain('id="open-workspace"');
    expect(html).toContain('id="workspace-overlay"');
    expect(html).toContain("No access key is required");
    expect(html).toContain("Private is the default");
    expect(html).toContain('/assets/world-map.svg');
    expect(html).not.toContain('/assets/bnb-worker-reference.png');
    expect(html).not.toContain('/assets/global-worker-map.png');
    expect(html).toContain('id="public-job-detail"');
    expect(html).toContain('id="public-job-artifact"');
    expect(html).toContain('id="public-job-timeline"');
    expect(html).toContain('id="docs-binance"');
    expect(html).toContain('class="swiss-hero"');
    expect(html).not.toContain('class="swiss-map"');
    expect(html).not.toContain('class="map-dots"');
    expect(html).toContain('class="provider-strip"');
    expect(html).toContain('class="landing-benefits"');
    expect(html).toContain('data-public-route="home"');
    expect(html).toContain('data-public-route="explore"');
    expect(html).toContain('data-public-route="network"');
    expect(html).toContain('data-public-route="docs"');
    expect(html).toContain('id="public-jobs-list"');
    expect(html).toContain('id="public-worker-map"');
    expect(html).toContain('id="public-docs"');
    expect(html).toContain('id="publish-job"');
    expect(html).toContain('data-route="dashboard"');
    expect(html).toContain('data-route="jobs"');
    expect(html).toContain('data-route="workers"');
    expect(html).toContain('data-route="submit"');
    expect(html).toContain('data-route="inbox"');
    expect(html).toContain('data-route="logs"');
    expect(html).toContain('id="job-detail-view"');
    expect(html).toContain('id="job-form"');
    expect(html).toContain('id="service-id"');
    expect(html).toContain('id="jobs-table-body"');
    expect(html).toContain('id="inbox-list"');
    expect(html).not.toContain("user-secret");
  });

  it("uses the selected Swiss-light system with real local brand assets and honest beta copy", async () => {
    const [html, css] = await Promise.all([
      readFile(join(root, "public", "index.html"), "utf8"),
      readFile(join(root, "public", "styles.css"), "utf8"),
    ]);
    expect(css).toContain("--yellow:#f0b90b");
    expect(css).toContain("--paper:#f7f7f2");
    expect(css).toContain("--ink:#0a0a0a");
    expect(css).toContain("[hidden]{display:none!important}");
    expect(css).toContain("@media(max-width:760px)");
    expect(css).toContain(".app-nav");
    expect(css).toContain(".swiss-hero");
    expect(css).not.toContain(".swiss-map");
    expect(css).not.toContain(".map-dots");
    expect(css).toContain(".provider-strip");
    expect(css).toContain(".landing-benefits");
    expect(css).toContain("grid-template-columns:minmax(0,1000px) minmax(360px,1fr)");
    expect(css).toContain("aspect-ratio:15/7");
    expect(css).toContain("align-items:start");
    expect(css).toContain(".stat-grid");
    expect(css).toContain(".jobs-table");
    expect(html).toContain('/assets/logos/bnb-chain.ico');
    expect(html).toContain('/assets/logos/openai.svg');
    expect(html).toContain('/assets/logos/anthropic.svg');
    expect(html).toContain('/assets/logos/ollama.png');
    expect(html).toContain('/assets/logos/higgsfield.png');
    expect(html).toContain('/assets/logos/deepseek.svg');
    expect(html).toContain('DeepSeek');
    expect(html).toContain('Anthropic jobs require <code>ANTHROPIC_API_KEY</code>');
    expect(html).toContain('text.openai.codex');
    expect(html).not.toContain('text.anthropic.claude-code');
    expect(html).toContain("Free private beta");
    expect(html).not.toContain("Connect Wallet");
    expect(html).not.toContain("Earn on BNB");
    expect(html).not.toContain("Payment (BNB)");
    expect(html).not.toContain('/assets/bnb-ai-command-center.webp');
  });

  it("routes between real data views and never fabricates wallet or worker telemetry", async () => {
    const source = await readFile(join(root, "public", "app.js"), "utf8");
    expect(source).toContain("history.pushState");
    expect(source).toContain("renderDashboard");
    expect(source).toContain("renderJobsTable");
    expect(source).toContain("renderInbox");
    expect(source).toContain("renderLogs");
    expect(source).toContain("openJobDetail");
    expect(source).toContain("function openJobDetail(id, push = true)");
    expect(source).toContain("openJobDetail(selectedJobId, false)");
    expect(source).toContain("/api/jobs");
    expect(source).toContain("/api/explorer/jobs");
    expect(source).toContain('publicRequestApi("/api/requests"');
    expect(source).toContain('"x-request-token"');
    expect(source).toContain("PUBLIC_REQUEST_KEY");
    expect(source).toContain("publicRoutes");
    expect(source).toContain("renderPublicExplorer");
    expect(source).toContain("openPublicJobDetail");
    expect(source).toContain("/api/explorer/jobs/");
    expect(source).toContain("isPublic");
    expect(source).toContain("/api/services");
    expect(source).toContain("serviceId");
    expect(source).toContain("document.createElement(\"img\")");
    expect(source).toContain("document.createElement(\"video\")");
    expect(source).toContain("Authorization");
    expect(source).toContain("sessionStorage");
    expect(source).not.toContain("localStorage");
    expect(source).not.toContain("innerHTML =");
    expect(source).not.toContain("Connect Wallet");
    expect(source).not.toContain("Total Workers: 156");
  });
});
