import { describe, expect, it, vi } from "vitest";
import { generateWithOllama } from "../src/ollama-adapter.js";
import { runWorkerOnce } from "../src/worker.js";

describe("Ollama adapter", () => {
  it("sends a bounded non-streaming request and returns the generated text", async () => {
    const fetcher = vi.fn(async (input: URL | RequestInfo, init?: RequestInit) => {
      const url = String(input);
      const body = JSON.parse(String(init?.body));
      expect(body).toMatchObject({ model: "llama3.2", prompt: "hello", stream: false });
      return new Response(JSON.stringify({ response: "hello human" }), { status: 200 });
    });
    const output = await generateWithOllama({ baseUrl: "http://127.0.0.1:11434", model: "llama3.2", prompt: "hello", fetcher });
    expect(output).toBe("hello human");
  });
});

describe("worker cycle", () => {
  it("claims one job, runs the adapter and completes the same lease", async () => {
    const requests: Array<{ url: string; init?: RequestInit }> = [];
    const fetcher = vi.fn(async (url: string, init?: RequestInit) => {
      requests.push({ url, init });
      if (url.endsWith("/api/worker/claim")) {
        return new Response(JSON.stringify({
          leaseToken: "lease-token-with-enough-entropy",
          job: { id: "job-1", prompt: "write a caption and generate an image", serviceId: "text.openai.sol", requirements: ["text", "image"] },
          serviceIds: ["text.openai.sol", "image.openai.gpt-image-2"],
          attempt: { id: "11111111-1111-4111-8111-111111111111" }
        }), { status: 200, headers: { "content-type": "application/json" } });
      }
      return new Response(JSON.stringify({ state: "succeeded" }), { status: 200, headers: { "content-type": "application/json" } });
    });

    const outcome = await runWorkerOnce({
      apiUrl: "https://network.example",
      workerId: "worker-1",
      workerToken: "worker-secret",
      capabilities: ["text.openai.sol", "image.openai.gpt-image-2"],
      fetcher,
      execute: async (job) => `generated by ${job.serviceIds.join("+")}: ${job.prompt}`
    });

    expect(outcome).toBe("completed");
    expect(requests).toHaveLength(2);
    expect(JSON.parse(String(requests[0]!.init?.body))).toEqual({
      capabilities: ["text.openai.sol", "image.openai.gpt-image-2"],
      acceptPublicRequests: false
    });
    expect(JSON.parse(String(requests[1]!.init?.body))).toEqual({
      leaseToken: "lease-token-with-enough-entropy",
      output: "generated by text.openai.sol+image.openai.gpt-image-2: write a caption and generate an image"
    });
  });

  it("rejects a lease containing a service the worker did not advertise", async () => {
    const fetcher = vi.fn(async () => new Response(JSON.stringify({
      leaseToken: "lease-token-with-enough-entropy",
      job: { id: "job-1", prompt: "generate an image", serviceId: "image.openai.gpt-image-2", requirements: ["image"] },
      serviceIds: ["image.openai.gpt-image-2"],
      attempt: { id: "11111111-1111-4111-8111-111111111111" }
    }), { status: 200, headers: { "content-type": "application/json" } }));

    await expect(runWorkerOnce({
      apiUrl: "https://network.example",
      workerId: "worker-1",
      workerToken: "worker-secret",
      capabilities: ["text.ollama"],
      fetcher,
      execute: async () => "should not run"
    })).rejects.toThrow("unapproved service");
  });
});
